### PR TITLE
Added "Broadwell EP" (E5-2660 v4)

### PR DESCRIPTION
**Pull request by maltris**

### CODE REVIEW

**Comment by ertyu** [comment]
Is the default core selection for OGR and RC5 correct for the CPU after the patch?

**Comment by maltris** [comment]
In my case it was (recognized 56 cores) in a dual-cpu setup - 28 per cpu - 14 cores, 28 threads.

**Comment by maltris** [comment]
Is this going to be merged? :+1:

**Comment by maltris** [comment]
Bump. :wave:

**Comment by maltris** [comment]
:hand:

**Comment by bovine** [comment]
Can you update your branch so we can merge? There was a merge conflict with another pull request.

**Comment by maltris** [comment]
Hello!

You can just merge it manually, no?

**Comment by bovine** [comment]
Manually merged.  Thanks!

**Pull request closed without merging**
